#!/usr/bin/env python3
"""
phiweaver.curation_examples — the validated curation-example library.

Reads the human-validated worked examples under ``07-Standards/curation-examples/`` (each a
markdown file with machine-readable tag frontmatter) and regenerates ``Curation-Examples-INDEX.md`` — an
enumerable, topic-grouped index. phiweaver retrieves the best-matching examples from this
library as references when drafting a new curation of a similar case; a curator browses the
same index.

This is *retrieval*, not model training: the library grows as validated examples are added,
and matching examples are read as in-context references each time. An example is a **draft**
until a curator reviews it and sets ``status: validated`` — only validated examples should be
used as references, since a wrong example would propagate its mistakes.

Tag values come from ``07-Standards/curation-examples/TAGS.md`` (a small controlled
vocabulary); the shape of an example is in ``_TEMPLATE.md``.

Usage (from the repo root):
    python3 -m phiweaver.curation_examples          # rewrite Curation-Examples-INDEX.md
    python3 -m phiweaver.curation_examples --check   # verify index current + contract (no writes)
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import List, Optional

from phiweaver import repo_root
from phiweaver.registry import parse_frontmatter   # reuse the frontmatter parser

EXAMPLES_DIR = "07-Standards/curation-examples"
INDEX_PATH = EXAMPLES_DIR + "/Curation-Examples-INDEX.md"
REQUIRED_FIELDS = ("type", "status", "topics", "source")
VALID_STATUS = ("draft", "validated")
_SKIP_NAMES = {"Curation-Examples-INDEX.md", "TAGS.md"}

# PHI-Canto's own annotation types — the coverage target for the gold-standard library.
# (name, sessions-with-this-type) from canto.phi-base.org/tools/sessions_with_type_list;
# the count is a rough prevalence, so coverage can be prioritised by frequency. Kept in
# sync with the `annotation_types` vocabulary in TAGS.md; ordered most-common first.
PHI_CANTO_ANNOTATION_TYPES = (
    ("disease_name", 339),
    ("pathogen_host_interaction_phenotype", 333),
    ("pathogen_phenotype", 281),
    ("biological_process", 263),
    ("molecular_function", 223),
    ("cellular_component", 152),
    ("physical_interaction", 99),
    ("wt_rna_expression", 95),
    ("gene_for_gene_phenotype", 58),
    ("host_phenotype", 17),
    ("post_translational_modification", 14),
    ("wt_protein_expression", 4),
)
_CANONICAL_ANNOTATION_TYPES = {name for name, _ in PHI_CANTO_ANNOTATION_TYPES}


def _as_list(value) -> List[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [v for v in value if v]
    return [value]


class Example:
    def __init__(self, path: Path, meta: dict):
        self.path = path
        self.name = path.stem
        self.meta = meta
        self.status = meta.get("status") or ""
        self.topics = _as_list(meta.get("topics"))
        self.annotation_types = _as_list(meta.get("annotation_types"))
        self.evidence = _as_list(meta.get("evidence"))
        self.pathogen = meta.get("pathogen") or ""
        self.host = meta.get("host") or ""
        self.source = meta.get("source") or ""


def discover_examples(examples_dir: Path) -> List[Example]:
    """Every ``type: curation-example`` markdown file in the folder (skips meta files and
    underscore-prefixed files like ``_TEMPLATE.md``)."""
    out: List[Example] = []
    if not examples_dir.exists():
        return out
    for md in sorted(examples_dir.glob("*.md")):
        if md.name.startswith("_") or md.name in _SKIP_NAMES:
            continue
        meta = parse_frontmatter(md.read_text(encoding="utf-8"))
        if meta.get("type") != "curation-example":
            continue
        out.append(Example(md, meta))
    return out


def render_index(examples: List[Example]) -> str:
    validated = [e for e in examples if e.status == "validated"]
    out = [
        "# Curation Example Library",
        "",
        "<!-- GENERATED by `python3 -m phiweaver.curation_examples`. Do not edit by hand;",
        "     edit each example's frontmatter and regenerate. -->",
        "",
        "Human-validated worked curations that phiweaver retrieves as references when drafting "
        "a new curation of a similar case (retrieval, not model training). Each is one markdown "
        "file with tag frontmatter — see `_TEMPLATE.md` and the controlled vocabulary in "
        "`TAGS.md`.",
        "",
        "**An example is a _draft_ until a curator reviews it and sets `status: validated`.** "
        "Only validated examples should be used as references.",
        "",
        f"**{len(validated)} validated**, {len(examples) - len(validated)} draft, "
        f"{len(examples)} total.",
        "",
    ]
    out += render_coverage(validated)

    if not examples:
        out += ["_No examples yet. Copy `_TEMPLATE.md` to a new file and curate one — "
                "phiweaver drafts it; a curator reviews it and sets `status: validated`._", ""]
        return "\n".join(out)

    out += ["## All examples", "",
            "| Example | Status | Topics | Annotation types | Source |",
            "| --- | --- | --- | --- | --- |"]
    for e in examples:
        badge = "✅ validated" if e.status == "validated" else "✏️ draft"
        topics = ", ".join(e.topics) or "—"
        atypes = ", ".join(e.annotation_types) or "—"
        out.append(f"| [[{e.name}]] | {badge} | {topics} | {atypes} | {e.source or '—'} |")
    out.append("")

    all_topics = sorted({t for e in examples for t in e.topics})
    if all_topics:
        out += ["## By topic", "",
                "_The same example appears under every topic it is tagged with._", ""]
        for topic in all_topics:
            out.append(f"### {topic}")
            for e in examples:
                if topic in e.topics:
                    badge = "✅" if e.status == "validated" else "✏️"
                    tail = f" — {e.pathogen}" if e.pathogen else ""
                    out.append(f"- {badge} [[{e.name}]]{tail}")
            out.append("")
    return "\n".join(out)


def render_coverage(validated: List[Example]) -> List[str]:
    """A checklist of PHI-Canto's annotation types vs the validated library, so the gaps
    that still need a gold-standard example are visible at a glance."""
    covered = {t: 0 for t, _ in PHI_CANTO_ANNOTATION_TYPES}
    for e in validated:
        for t in e.annotation_types:
            if t in covered:
                covered[t] += 1
    n_covered = sum(1 for c in covered.values() if c)
    total = len(PHI_CANTO_ANNOTATION_TYPES)
    out = [
        "## Coverage — PHI-Canto annotation types",
        "",
        "_The gold-standard library aims to cover every PHI-Canto annotation type (coverage, "
        "not volume). `Sessions` is how common the type is in PHI-Canto — a rough priority. "
        "Generated from the `annotation_types` frontmatter of **validated** examples only._",
        "",
        f"**{n_covered}/{total} types covered.**",
        "",
        "| Annotation type | Sessions | Examples | Status |",
        "| --- | --- | --- | --- |",
    ]
    for name, sessions in PHI_CANTO_ANNOTATION_TYPES:
        n = covered[name]
        status = f"✅ {n}" if n else "⬜ gap"
        out.append(f"| {name} | {sessions} | {n or '—'} | {status} |")
    out.append("")
    return out


def validate_examples(examples: List[Example]) -> List[str]:
    """Contract problems (empty = all good)."""
    problems: List[str] = []
    for e in examples:
        for field in REQUIRED_FIELDS:
            if field not in e.meta:
                problems.append(f"{e.name}: missing frontmatter field '{field}'")
        if e.status and e.status not in VALID_STATUS:
            problems.append(
                f"{e.name}: status '{e.status}' not in {VALID_STATUS}")
        if "topics" in e.meta and not e.topics:
            problems.append(f"{e.name}: at least one topic is required")
        for atype in e.annotation_types:
            if atype not in _CANONICAL_ANNOTATION_TYPES:
                problems.append(
                    f"{e.name}: annotation_type '{atype}' is not a PHI-Canto type "
                    f"(see TAGS.md)")
    return problems


def check(root: Optional[Path] = None) -> List[str]:
    root = root or repo_root()
    examples = discover_examples(root / EXAMPLES_DIR)
    problems = validate_examples(examples)
    current = render_index(examples)
    existing_path = root / INDEX_PATH
    existing = existing_path.read_text(encoding="utf-8") if existing_path.exists() else None
    if existing != current:
        problems.append(
            f"{INDEX_PATH} is out of date — run `python3 -m phiweaver.curation_examples`")
    return problems


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="PHI-Weaver curation-example index.")
    p.add_argument("--check", action="store_true",
                   help="validate the contract and that the index is current (no writes)")
    args = p.parse_args(argv)

    root = repo_root()
    if args.check:
        problems = check(root)
        if problems:
            print("❌ curation-examples check failed:")
            for prob in problems:
                print(f"   - {prob}")
            return 1
        print("✅ curation-examples check passed.")
        return 0

    examples = discover_examples(root / EXAMPLES_DIR)
    (root / INDEX_PATH).write_text(render_index(examples), encoding="utf-8")
    print(f"✅ wrote {INDEX_PATH} ({len(examples)} example(s)).")
    problems = validate_examples(examples)
    if problems:
        print("⚠️  but the contract has problems:")
        for prob in problems:
            print(f"   - {prob}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
