#!/usr/bin/env python3
"""
phiweaver.registry — the module/skill registry.

Reads the machine-readable frontmatter of every ``skills/*/SKILL.md`` (name, description,
``backing_script``, ``tests``, ``inputs``, ``outputs``) and:

- **regenerates** ``skills/REGISTRY.md`` — an enumerable index of available modules and
  their backing tools/tests (default action);
- **validates** the contract (``--check``): required fields present, and every declared
  backing_script / tests path actually exists; also that ``REGISTRY.md`` is up to date.

No third-party deps: a tiny frontmatter parser handles the simple ``key: scalar`` and
block-list (``- item``) shapes used here. See ``docs/ADDING-A-MODULE.md``.

Usage (from the repo root):
    python3 -m phiweaver.registry            # rewrite skills/REGISTRY.md
    python3 -m phiweaver.registry --check    # verify contract + registry currency (CI)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List, Optional

from phiweaver import repo_root

REQUIRED_FIELDS = ("name", "description", "backing_script", "tests", "inputs", "outputs")
REGISTRY_PATH = "skills/REGISTRY.md"


# ----------------------------------------------------------------- frontmatter

def parse_frontmatter(text: str) -> dict:
    """Parse a leading ``---`` YAML-ish frontmatter block.

    Supports ``key: scalar`` (with ``null`` -> None), and block lists where ``key:`` is
    followed by indented ``- item`` lines. Sufficient for SKILL.md; not a full YAML parser.
    """
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    data: dict = {}
    key: Optional[str] = None
    for raw in lines[1:]:
        if raw.strip() == "---":
            break
        stripped = raw.strip()
        if stripped.startswith("- ") and key is not None and isinstance(data.get(key), list):
            data[key].append(stripped[2:].strip())
            continue
        if ":" in raw and not raw.startswith((" ", "\t")):
            k, _, rest = raw.partition(":")
            key = k.strip()
            rest = rest.strip()
            if rest == "":
                data[key] = []            # a block list (or empty) follows
            elif rest.lower() == "null":
                data[key] = None
            else:
                data[key] = rest.strip().strip('"').strip("'")
    return data


def _as_list(value) -> List[str]:
    if value is None:
        return []
    if isinstance(value, list):
        return [v for v in value if v]
    return [value]


# --------------------------------------------------------------------- model

class Skill:
    def __init__(self, folder: Path, meta: dict):
        self.folder = folder
        self.meta = meta
        self.name = meta.get("name") or folder.name
        self.description = meta.get("description") or ""
        self.backing_scripts = _as_list(meta.get("backing_script"))
        self.tests = _as_list(meta.get("tests"))
        self.inputs = _as_list(meta.get("inputs"))
        self.outputs = _as_list(meta.get("outputs"))


def discover_skills(skills_dir: Path) -> List[Skill]:
    skills = []
    for skill_md in sorted(skills_dir.glob("*/SKILL.md")):
        meta = parse_frontmatter(skill_md.read_text(encoding="utf-8"))
        skills.append(Skill(skill_md.parent, meta))
    return skills


# ------------------------------------------------------------------- render

def render_registry(skills: List[Skill]) -> str:
    out = [
        "# Skill / Module Registry",
        "",
        "<!-- GENERATED by `python3 -m phiweaver.registry`. Do not edit by hand;",
        "     edit each skill's SKILL.md frontmatter and regenerate. -->",
        "",
        "Enumerable index of the reusable curation modules. Each is a skill "
        "(`skills/<name>/SKILL.md`) optionally backed by a deterministic tool in "
        "`phiweaver/` with tests in `tests/`. See `docs/ADDING-A-MODULE.md`.",
        "",
        "| Skill | When to use | Backing tool(s) | Tests |",
        "| --- | --- | --- | --- |",
    ]
    for s in skills:
        tools = "<br>".join(f"`{b}`" for b in s.backing_scripts) or "_(reasoning-only)_"
        tests = "<br>".join(f"`{t}`" for t in s.tests) or "—"
        desc = s.description.replace("|", "\\|")
        out.append(f"| `{s.name}` | {desc} | {tools} | {tests} |")
    out.append("")
    return "\n".join(out)


# ----------------------------------------------------------------- validate

def validate_skills(skills: List[Skill], root: Path) -> List[str]:
    """Return a list of contract problems (empty = all good)."""
    problems: List[str] = []
    if not skills:
        problems.append("no skills found under skills/*/SKILL.md")
    for s in skills:
        for field in REQUIRED_FIELDS:
            if field not in s.meta:
                problems.append(f"{s.folder.name}: missing frontmatter field '{field}'")
        for rel in s.backing_scripts:
            if not (root / rel).exists():
                problems.append(f"{s.name}: backing_script not found: {rel}")
        for rel in s.tests:
            if not (root / rel).exists():
                problems.append(f"{s.name}: tests path not found: {rel}")
    return problems


def check(root: Optional[Path] = None) -> List[str]:
    """Full contract check used by CI / the smoke test: validation + registry currency."""
    root = root or repo_root()
    skills = discover_skills(root / "skills")
    problems = validate_skills(skills, root)
    current = render_registry(skills)
    existing_path = root / REGISTRY_PATH
    existing = existing_path.read_text(encoding="utf-8") if existing_path.exists() else None
    if existing != current:
        problems.append(
            f"{REGISTRY_PATH} is out of date — run `python3 -m phiweaver.registry`")
    return problems


# --------------------------------------------------------------------- CLI

def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="PHI-Weaver skill/module registry.")
    p.add_argument("--check", action="store_true",
                   help="validate the contract and that REGISTRY.md is current (no writes)")
    args = p.parse_args(argv)

    root = repo_root()
    if args.check:
        problems = check(root)
        if problems:
            print("❌ registry check failed:")
            for prob in problems:
                print(f"   - {prob}")
            return 1
        print("✅ registry check passed: contract valid and REGISTRY.md current.")
        return 0

    skills = discover_skills(root / "skills")
    problems = validate_skills(skills, root)
    (root / REGISTRY_PATH).write_text(render_registry(skills), encoding="utf-8")
    print(f"✅ wrote {REGISTRY_PATH} ({len(skills)} skills).")
    if problems:
        print("⚠️  but the contract has problems:")
        for prob in problems:
            print(f"   - {prob}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
