#!/usr/bin/env python3
"""Assemble the PHI-Weaver -> LLM-judge handover bundle into one markdown file.

Concatenates the convention material an external model (e.g. GPT-5.5) needs to act as a
convention-aware judge / pre-review critic of PHI-Weaver curation drafts, with a vault-path
index at the top. Output is a GENERATED artifact -- edit the source files, then rerun:

    python3 scripts/build_judge_handover.py

Writes docs/phiweaver-judge-handover.md. See the parked design note
11-CLAUDE-AI/SESSION-LOGS/2026-07-09-llm-as-judge-discussion.md for the rationale.
"""
from pathlib import Path
from datetime import date

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "docs" / "phiweaver-judge-handover.md"

# (vault-relative path, role blurb) in reading order
FILES = [
    ("07-Standards/curation-benchmarking/README.md",
     "Scorecard rubric — the criteria the judge should grade against"),
    ("07-Standards/curation-examples/TAGS.md",
     "Controlled vocabulary (annotation types, topics, evidence) used in examples"),
    ("07-Standards/curation-examples/INDEX.md",
     "Index of the worked examples + PHI-Canto annotation-type coverage"),
    ("07-Standards/curation-examples/_TEMPLATE.md",
     "Template showing the shape of a worked curation example"),
    ("07-Standards/Ontology-Terms-Reference.md",
     "Ontology reference (PHIPO / PHIDO / GO / BRENDA) conventions"),
    ("07-Standards/UniProtKB-Gene-Identification-Guide.md",
     "How genes/proteins are resolved to UniProtKB accessions"),
    ("07-Standards/Genetic Nomenclature.md",
     "Gene/allele naming conventions"),
    ("07-Standards/Effector-curation-2026-04-15/"
     "Curation Methodologies for Pathogen Effector Curation.md",
     "Effector curation methodology (gene-for-gene, guard/decoy, recognition)"),
    ("07-Standards/Effector-curation-2026-04-15/"
     "GO-terms used for gene-for-gene-entries.md",
     "GO terms conventionally used for gene-for-gene / effector entries"),
    ("skills/REGISTRY.md",
     "What each curation step is supposed to produce (module registry)"),
    ("07-Standards/curation-examples/PMID26177154-Fol-I7-gene-for-gene.md",
     "WORKED EXAMPLE — gene-for-gene (Fol effectors x tomato I-7)"),
    ("07-Standards/curation-examples/"
     "PMID35468894-PINE1-effector-PGIP-physical-interaction.md",
     "WORKED EXAMPLE — effector physical interaction (PINE1 x PGIP)"),
    ("07-Standards/curation-examples/PMID37177781-AvrPi9-OsRGLG5-protein-level.md",
     "WORKED EXAMPLE — protein-level effect (AvrPi9 x OsRGLG5)"),
    ("07-Standards/curation-examples/PMID23498959-creD-RLCK185-phosphorylation.md",
     "WORKED EXAMPLE — phosphorylation (creD / RLCK185)"),
    ("07-Standards/curation-examples/PMID39787257-FgKnr4-cell-wall-stress.md",
     "WORKED EXAMPLE — cell-wall stress phenotype (FgKnr4)"),
]


def anchor(role):
    return "worked-example" if role.startswith("WORKED EXAMPLE") else "reference"


def build():
    parts = [f"""# PHI-Weaver → LLM-as-judge handover bundle

<!-- GENERATED by `python3 scripts/build_judge_handover.py`. Do not edit by hand;
     edit the source files listed in the index below and regenerate. -->

*Generated {date.today().isoformat()} from the PHI-Weaver vault. Single-file convention
primer for an external model (e.g. GPT-5.5) acting as an independent judge / pre-review
critic of PHI-Weaver curation drafts.*

## How to use this
1. Give the model **this whole file once** as a convention primer, then per paper add
   the publication, the phiweaver draft, the PHI-Canto entry queue, and the blank scorecard.
2. Ask it to critique/score the draft **against the rubric and conventions below** —
   not against its own idea of a correct curation. That is what turns it from a naïve
   outsider into a convention-aware reviewer.
3. Treat its output as **candidate issues for a human to adjudicate**, not a verdict.
   The human gold standard is a strong reference, not ground truth — a judge–human
   disagreement is investigated both ways (see the parked design note,
   `11-CLAUDE-AI/SESSION-LOGS/2026-07-09-llm-as-judge-discussion.md`).

## ⚠️ Leakage note
The worked examples below are human-validated gold standards. If you ever judge a paper
that **is** one of these (by PMID), remove that example from the primer for that run so
the judge can't grade against the answer key. (Not an issue for papers with no gold standard.)

## Where these files live in the vault
| # | Role | Vault path |
| - | ---- | ---------- |"""]

    for i, (path, role) in enumerate(FILES, 1):
        parts.append(f"| {i} | {role} | `{path}` |")

    parts.append("\n---\n")

    for i, (path, role) in enumerate(FILES, 1):
        f = REPO / path
        body = f.read_text(encoding="utf-8") if f.exists() else "_(file not found)_\n"
        parts.append(f"""<!-- ===== FILE {i}/{len(FILES)} :: {anchor(role)} ===== -->
## {i}. {role}
**Vault path:** `{path}`

````markdown
{body.rstrip()}
````

---
""")

    OUT.write_text("\n".join(parts), encoding="utf-8")
    text = OUT.read_text(encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO)} — "
          f"{OUT.stat().st_size / 1024:.1f} KB, {text.count(chr(10))} lines, "
          f"{len(FILES)} source files")


if __name__ == "__main__":
    build()
